# Generated by Django 5.1.1 on 2025-06-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
