# Generated by Django 5.1.1 on 2024-10-17 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0008_alter_equipo_modelo'),
        ('IA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloia',
            name='variable_objetivo',
            field=models.CharField(default='max_activity', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cpu_total_load', models.FloatField()),
                ('cpu_core_max_load', models.FloatField()),
                ('cpu_core_max_temp', models.FloatField()),
                ('cpu_core_avg_temp', models.FloatField()),
                ('cpu_avg_core_clock', models.FloatField()),
                ('cpu_bus_speed_clock', models.FloatField()),
                ('cpu_package_power', models.FloatField()),
                ('cpu_cores_power', models.FloatField()),
                ('cpu_memory_power', models.FloatField()),
                ('cpu_core_voltage', models.FloatField()),
                ('memory_load', models.FloatField()),
                ('memory_available', models.FloatField()),
                ('memory_used', models.FloatField()),
                ('avg_used_space', models.FloatField()),
                ('avg_read', models.FloatField()),
                ('avg_write', models.FloatField()),
                ('avg_activity', models.FloatField()),
                ('max_used_space', models.FloatField()),
                ('max_read', models.FloatField()),
                ('max_write', models.FloatField()),
                ('max_activity', models.FloatField()),
                ('failure_percentage', models.FloatField()),
                ('is_manual', models.BooleanField(default=False)),
                ('modelo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipos.modelo')),
                ('modelo_ia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IA.modeloia')),
            ],
        ),
    ]
