# Generated by Django 5.1.1 on 2024-11-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0004_modeloia_componente'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloia',
            name='scaler',
            field=models.FileField(blank=True, null=True, upload_to='modelos/'),
        ),
    ]
