# Generated by Django 5.1.1 on 2024-10-07 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Areas', '0001_initial'),
        ('Equipos', '0002_alter_cpu_equipo_alter_disk_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Areas.area'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
