# Generated by Django 5.1.1 on 2024-10-07 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Areas', '0001_initial'),
        ('Equipos', '0003_alter_equipo_area_delete_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Areas.area'),
        ),
    ]
