# Generated by Django 5.1.1 on 2024-10-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0004_alter_equipo_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='area',
        ),
    ]
