# Generated by Django 5.1.1 on 2024-10-16 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0006_equipo_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Equipos.modelo'),
        ),
    ]
