# Generated by Django 5.1.1 on 2024-10-17 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0007_modelo_equipo_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipo_set', to='Equipos.modelo'),
        ),
    ]
