# Generated by Django 5.1.1 on 2025-06-16 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0008_alter_equipo_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='disk',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Equipos.estadoalerta'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='disk',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Equipos.estadoalerta'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Equipos.estadoalerta'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
