# Generated by Django 5.1.1 on 2024-09-13 16:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_total_load', models.FloatField()),
                ('cpu_core_max_load', models.FloatField()),
                ('cpu_core_max_temp', models.FloatField()),
                ('cpu_core_avg_temp', models.FloatField()),
                ('cpu_avg_core_clock', models.FloatField()),
                ('cpu_bus_speed_clock', models.FloatField()),
                ('cpu_package_power', models.FloatField()),
                ('cpu_cores_power', models.FloatField()),
                ('cpu_memory_power', models.FloatField()),
                ('cpu_core_voltage', models.FloatField()),
                ('memory_load', models.FloatField()),
                ('memory_available', models.FloatField()),
                ('memory_used', models.FloatField()),
                ('avg_used_space', models.FloatField()),
                ('avg_read', models.FloatField()),
                ('avg_write', models.FloatField()),
                ('avg_activity', models.FloatField()),
                ('max_used_space', models.FloatField()),
                ('max_read', models.FloatField()),
                ('max_write', models.FloatField()),
                ('max_activity', models.FloatField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipos.equipo')),
            ],
        ),
    ]
