# Generated by Django 5.1.1 on 2024-09-16 03:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0002_alter_cpu_equipo_alter_disk_equipo_and_more'),
        ('Sensores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('error', models.TextField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipos.equipo')),
            ],
        ),
    ]
